### ISSUE TITLE
Release a new version and update wiki

### ISSUE THREAD

**Issue by mitar** [trac-hacks/trac-mathjax#7]
@rjollos, I added you as an owner on PyPi for this package as well. I think we should release a new version of it as well.

BTW, why is on [wiki](https://trac-hacks.org/wiki/TracMathJaxPlugin) said that this is not maintained? I mean, I still maintain it to the degree needed. :-)

Now, on the wiki I also see that the repository is pointed to the Bitbucket, where it seems that there [are new commits as well](https://bitbucket.org/kisielk/tracmathjaxplugin/commits/all). Maybe we should consolidate all that into one repo, one project?

**Comment by rjollos** [comment]
> BTW, why is on wiki said that this is not maintained? I mean, I still maintain it to the degree needed. :-)

You aren't listed as the project maintainer in the database. It appears you just forked the project. See [AdoptingHacks](https://trac-hacks.org/wiki/AdoptingHacks).

> Maybe we should consolidate all that into one repo, one project?

Sounds like a good idea. The project has been [offered for adoption](https://groups.google.com/forum/#!topic/trac-hacks/_C8yjXyikBk).

**Comment by mitar** [comment]
I am realizing I do not have time to maintain this package either anymore. :-(

**Comment by rjollos** [comment]
[MathJaxPlugin 0.1.5](https://pypi.python.org/pypi/MathJaxPlugin/0.1.5) published to PyPI.
